name       : haskell-resourcet
version    : 1.2.4.1
release    : 3
source     :
    - https://hackage.haskell.org/package/resourcet-1.2.4.1/resourcet-1.2.4.1.tar.gz : 22e02f18c6bc66430578ccddffd7a0fc616313618edf3bf4f4d393593ae1c740
license    : BSD-3-Clause
component  : programming.haskell
summary    : Deterministic allocation and freeing of scarce resources
description: |
    Deterministic allocation and freeing of scarce resources
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-primitive-devel
    - haskell-unliftio-core-devel
rundeps    :
    - devel:
        - haskell-exceptions-devel
        - haskell-primitive-devel
        - haskell-unliftio-core-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
