name       : haskell-resourcet
version    : 1.1.9
release    : 1
source     :
    - http://hackage.haskell.org/package/resourcet-1.1.9/resourcet-1.1.9.tar.gz : 5a1999d26b896603cab8121b77f36723dc50960291872b691ff4a9533e162ef5
license    : BSD-3-Clause
component  : programming.haskell
summary    : Deterministic allocation and freeing of scarce resources
description: |
    Deterministic allocation and freeing of scarce resources
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-lifted-base
    - haskell-mmorph
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
