name       : haskell-resourcet
version    : 1.2.1
release    : 2
source     :
    - https://hackage.haskell.org/package/resourcet-1.2.1/resourcet-1.2.1.tar.gz : e765c12a6ec0f70efc3c938750060bc17569b99578aa635fd4da0c4d06fcf267
license    : BSD-3-Clause
component  : programming.haskell
summary    : Deterministic allocation and freeing of scarce resources
description: |
    Deterministic allocation and freeing of scarce resources
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-mmorph
    - haskell-primitive
    - haskell-unliftio-core
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
